In [4]:
#1
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr + 2)
print(arr * 3)
print(arr / 2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [17]:
#2
arr = np.array([1, 2, 3, 6, 4, 5]) 
arr = np.flip(arr)
print(arr)


x = np.array([1,2,3,4,5,1,2,1,1,1]) 
val, idx, count = np.unique(x, return_counts = True, return_inverse = True)

i = np.argmax(count)
print(val[i])

print(np.where(x == val[i]))

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

val, idx, count = np.unique(y, return_counts = True, return_inverse = True)

i = np.argmax(count)
print(val[i])

print(np.where(y == val[i]))

[5 4 6 3 2 1]
1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


In [23]:
#3 
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [33]:
#3
ashish = np.linspace(10, 100, 25)
print(ashish.ndim)
print(ashish.shape)
print(ashish.size)
print(ashish.dtype)
print(ashish.nbytes)

1
(25,)
25
float64
200


In [45]:
#4

ucs420_ashish = np.array((10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35)).reshape(3, 4)

print(np.mean(ucs420_ashish))
print(np.max(ucs420_ashish))
print(np.min(ucs420_ashish))
print(np.unique(ucs420_ashish))

reshaped_ucs420_ashish = ucs420_ashish.reshape(4, 3)
print(reshaped_ucs420_ashish, '\n')

resized_ucs420_ashish = np.resize(ucs420_ashish, (2,3))
print(resized_ucs420_ashish)


43.333333333333336
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]] 

[[10 20 30]
 [40 50 60]]
